import type { Metadata } from "next";
// import { AppProvider } from "./contexts/AppContext";
// import { Geist, Geist_Mono } from "next/font/google";
// import '../polyfills.js'
import { Buffer } from 'buffer';
import { createRequire } from 'module';
import SideNav from '@/app/Components/Molecules/SideNav'
// import { useWallet } from '@meshsdk/react';               
import Navbar  from '@/app/Components/Molecules/Navbar'
import "./globals.css";
import { Providers } from '@/app/Components/Organisms/Provider';
// import { AppProps } from "next/app";
// import type { AppProps } from 'next/app'



// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout( {
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  if (typeof window !== 'undefined') {
    window.Buffer = window.Buffer || Buffer;
    window.require = window.require || createRequire(import.meta.url);
  }

  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} 
        className="h-[100dvh] w-[100%] flex overflow-x-hidden "
      >
        <div className="none md:fixed md:flex-1/5 w-0 md:w-[20%] ">
          <SideNav />
        </div>
        
        
        <Providers >
          <div className='right-[0] md:ml-[20%] w-[100%] md:w-[80%] '>
            <Navbar />
            <div className="p-[1.5rem]">
              {children}
            </div>
            
          </div>
        </Providers>
      </body>
    </html>
  );
}
